name = "view-counter"

compatibility_date = "2023-07-24"
main = "./src/index.ts"

send_metrics = false
workers_dev = true

[placement]
# https://developers.cloudflare.com/workers/configuration/smart-placement/#enable-smart-placement-via-wrangler
mode = "smart"

[[d1_databases]]
binding = "ViewCounter" # i.e. available in your Worker on env.DB
database_id = "f7989e0a-3836-4d71-8d3a-404e8776e9f8" 
database_name = "view-counter"
